#ifndef __GUIMyFrame__
#define __GUIMyFrame__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>
#include <vector>
#include "Axis.h"
#include "Segment.h"

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame
{
private:
	Axis axis_limitations;
	//określa kolor krawędzi wyświetlany dla lewgo i prawego oka
	wxColor left_eye_color;
	wxColor right_eye_color;
	//określa w pikselach odległość między krawędziami dla oka prawego i lewego
	int edges_distance;
	//zapisywane w nim są informacje o odczytanych z pliku punktach - zapisane w zaprzyjaźnionej klasie Segment
	std::vector<Segment> data;
protected:
	// Handlers for MyFrame1 events.
	void WxPanel_Repaint(wxUpdateUIEvent& event);
	void m_button_load_geometry_click(wxCommandEvent& event);
	void m_button_save_click(wxCommandEvent& event);
	void m_button_background_click(wxCommandEvent& event);
    void m_button_color1_click(wxCommandEvent& event);
	void m_button_color2_click(wxCommandEvent& event);


	void Scrolls_Updated(wxScrollEvent& event);
public:
	/** Constructor */
	GUIMyFrame1(wxWindow* parent);
	//// end generated class members
	void Repaint();
	void draw_2d_line(wxDC *dc, const Point & begin_point, const Point & end_point);

	wxPanel* m_panel8;
	wxBitmap *saveIMG;
	wxFileDialog *WxOpenFileDialog1;
	wxPanel* m_panel1;
};

#endif // __GUIMyFrame1__
